[workspace]
resolver = "2"
members = [
    "crates/vidger",
    "crates/contracts",
    "crates/shared",
    "apps/cli",
]

[workspace.dependencies]
dotenv = "0.15.0"
anyhow = "1.0"
thiserror = "1.0.56"
bytes = "1.5"

# Logging
colored = "2.1"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"

# Async and Threads
tokio = { version = "1.36", features = ["full"] }
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
async-trait = "0.1.77"
futures = "0.3.30"
rayon = "1.5"

# Data structures
dashmap = { version = "5.5", features = ["rayon"] }
hashbrown = { version = "0.14", features = ["serde", "rayon", "inline-more"] }

# Serialization
serde = "1.0"
serde_json = "1.0"

# External world
reqwest = "0.11"
teloxide = { version = "0.12", features = ["macros"] }

# Database
rusqlite = { version = "0.31.0", features = ["bundled"] }

# EVM
alloy-primitives = { version = "0.6" }
ethers = { version = "2.0", features = [
    "abigen",
    "ws",
    "ipc",
    "rustls",
] }
revm = { version = "7.0", default-features = false, features = [
    "std",
    "serde",
    "memory_limit",
    "optional_eip3607",
    "optional_block_gas_limit",
    "optional_no_base_fee",
    "ethersdb",
] }
