[workspace]
resolver = "2"
members = [ # Dont use * for paths in the workspace (amm_protocol are not a crate)
    "apps/cli",
    "packages/shared",
    "packages/amm_protocol/protocol_uniswap_v2",
]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1", features = ['sync'] }

# EVM
ethers-providers = "2.0"
ethers-core = "2.0"
ethers-contract = { version = "2.0", default-features = false }
ethers = { version = "2.0", features = ["abigen", "ws", "rustls"] }
