[workspace]
resolver = "2"
members = [ # Dont use * for paths in the workspace
    "packages/shared",
    "packages/amm",
    "packages/mev",
    "apps/cli", "packages/contracts",
]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1", features = ['sync'] }

# EVM
ethers-core = "2.0"
ethers-providers = { version = "2.0", features = ["ws", "ipc"] }
ethers-contract = { version = "2.0", default-features = false }
ethers = { version = "2.0", features = ["abigen", "ws", "rustls"] }
