[package]
name = "vidger"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
ethers = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
teloxide = { workspace = true }

# Logging
colored = { workspace = true }
log = { workspace = true }
fern = { workspace = true }
chrono = { workspace = true }
