[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../crates/shared" }
vidger = { path = "../../crates/vidger" }
contracts = { path = "../../crates/contracts" }

dotenv = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
hashbrown = { workspace = true }

tokio = { workspace = true }
rayon = { workspace = true }

ethers = { workspace = true }
