[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../crates/shared" }
vidger = { path = "../../crates/vidger" }
contracts = { path = "../../crates/contracts" }

anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
ethers = { workspace = true }

dotenv = "0.15.0"
