[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../packages/shared" }
protocol_uniswap_v2 = { path = "../../packages/amm_protocol/protocol_uniswap_v2" }
tokio = { workspace = true }
anyhow = { workspace = true }
ethers = { workspace = true }

dotenv = "0.15.0"
