[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
contracts = { path = "../contracts" }
vidger = { path = "../vidger" }

tokio = { workspace = true }
tokio-stream = { workspace = true }
async-scoped = { workspace = true }

anyhow = { workspace = true }
dashmap = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
ethers = { workspace = true }
