[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
contracts = { path = "../contracts" }
vidger = { path = "../vidger" }

bytes = { workspace = true }
tokio = { workspace = true }
async-scoped = { workspace = true }
futures = { workspace = true }
rayon = { workspace = true }

anyhow = { workspace = true }
dashmap = { workspace = true }
hashbrown = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
reqwest = { workspace = true }

ethers = { workspace = true }
revm = { workspace = true }
