name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 🌐 Checkout code
      uses: actions/checkout@v4

    - name: ⚡ Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: 🦀 Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
      
    - name: 🔨 Build
      run: cargo build --release --verbose
      
    - name: 🔎 Tests
      run: cargo test --verbose

    - name: ☝️ Upload CLI
      uses: actions/upload-artifact@v4
      with:
        name: CLI
        path: target/release/cli
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🌐 Checkout code
        uses: actions/checkout@v4

      - name: 👇 Get CLI
        uses: actions/download-artifact@v4
        with:
          name: CLI

      - name: 🪢 Install sshpass
        run: sudo apt-get install sshpass

      - name: 📲 Send CLI to server
        run: |
          sshpass -v -p ${{ secrets.HOST_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ vars.HOST_IP }} mkdir -p ~/mev-chaser
          sshpass -v -p ${{ secrets.HOST_PASSWORD }} scp -o StrictHostKeyChecking=no cli root@${{ vars.HOST_IP }}:~/mev-chaser/cli

      - name: 📡 Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_IP }}
          username: root
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd ~
            chmod +x ~/mev-chaser/cli
        
